name: tresnet
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch>=2.0.1
  - torchaudio>=2.0.2
  - torchvision>=0.15.2
  - tensorboard>=2.11.2
  - tensorflow>=2.11.0
  - ipykernel
  - seaborn>=0.12.2
  - yaml>=0.2.5
  - tqdm
  - scikit-learn>=1.2.2
  - pip>=23
  - pip:
    - hydra-core==1.3
    - lightning>=2.0.6
    - snakemake==7.30.2
